#!/usr/bin/env bash
# Script: 0-world_wide_web
# Displays information about subdomains

display_info() {
    domain="$1"
    subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{p=1; next} p && NF {print}')
        record_type=$(echo "$dig_output" | awk '{print $2}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

display_info "$@"
