#!/usr/bin/env bash
# This script contains questions and answers related to MAC address & IP address.

# Question 6
# What is a MAC address?
# 1. The name of a network interface
# 2. The unique identifier of a network interface
# 3. A network interface

# Answer 6
echo "2"

# Question 7
# What is an IP address?
# 1. Is to devices connected to a network what postal address is to houses
# 2. The unique identifier of a network interface
# 3. Is a number that network devices use to connect to networks

# Answer 7
echo "1"
