#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Counter variable
count=1

# Using an until loop to display "Best School" 10 times
until [ $count -gt 10 ]; do
    echo "Best School"
    ((count++))
done

