#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages for certain iterations

# Counter variable
count=1

# Using a while loop to iterate from 1 to 20
while [ $count -le 20 ]; do
    # Using a case statement to display messages based on iteration
    case $count in
        4)
            echo $count
            echo "bad luck from China"
            ;;
        9)
            echo $count
            echo "bad luck from Japan"
            ;;
        17)
            echo $count
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac

    ((count++))
done

