#!/usr/bin/env bash

# Bash script to configure the resolution of hostnames on an Ubuntu server

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "Please run as root (sudo) to modify the hosts file."
    exit 1
fi

# Store the original /etc/hosts file
backup_file="/etc/hosts.bak"
cp /etc/hosts "$backup_file"

# Set the new IP addresses for localhost and facebook.com
new_localhost_ip="127.0.0.2"
new_facebook_ip="8.8.8.8"

# Update the /etc/hosts file
sed -i "s/^127.0.0.1[[:space:]]*localhost/127.0.0.1 localhost $new_localhost_ip/" /etc/hosts
sed -i "s/^.*facebook.com[[:space:]]*$/$new_facebook_ip facebook.com/" /etc/hosts

# Display a message to inform the user
echo "Hostnames configured successfully."

# Display the modified /etc/hosts file
echo "Updated /etc/hosts file:"
cat /etc/hosts

