#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig
sed -i 's/user\s*nginx;/user nginx/' /etc/nginx/nginx.conf
sed -i '/listen\s*80;/a listen 8080' /etc/nginx/nginx.conf
service nginx restart

